### ISSUE TITLE
python 3.10

### ISSUE THREAD

**Issue by xiaopihaiK** [aoki-h-jp/py-liquidation-map#7]
```
root@VM-4-9-ubuntu:~/test_liq# python3 v1.py
Traceback (most recent call last):
  File "/root/test_liq/v1.py", line 1, in <module>
    from liqmap.mapping import HistoricalMapping
  File "/usr/local/lib/python3.10/dist-packages/liqmap/__init__.py", line 4, in <module>
    from liqmap import download, mapping
  File "/usr/local/lib/python3.10/dist-packages/liqmap/mapping.py", line 10, in <module>
    from download import BinanceAggTradesDownload, BybitAggTradesDownloader
ImportError: cannot import name 'BinanceAggTradesDownload' from 'download' (/usr/local/lib/python3.10/dist-packages/download/__init__.py)

```

**Comment by aoki-h-jp** [comment]
@xiaopihaiK 
Thank you for reporting this.
When I tried to read my download.py, the code seemed to read a package called "download" in your PATH.
So I made a change to my package liq_map's download, so please check if the error is fixed.

**Comment by xiaopihaiK** [comment]
Thank you very much, this problem has been solved!
